Fix taint and untaint commands when in a workspace
hashicorp/terraform pull request #22467
Opened 2019-08-14 15:34 UTC by kulinacs

Fixes #22157. Removes DefaultStateFilepath as the default for the
-state flag, allowing workspaces to be used properly.

2019-09-25 14:57 UTC, atecce commented
🚢 🚢 🚢  :D

2019-11-11 15:14 UTC, lanoxx commented
Is this going to be considered for one of the upcoming 0.12.x patch releases?

2020-02-04 11:58 UTC, KptnKMan commented
It would be really great if this would be included in the next release.
This has been an issue for a long time now.

2020-09-04 09:01 UTC, phil-bee commented
It would be great if this could be included in the next release.

2020-09-28 13:00 UTC, mildwonkey requested changes
Thanks for working on this, @kulinacs ! The changes look great, but I've requested changes  to the tests. 

The test changes are absolutely not something we'd expect a community contributor to know, and if you'd rather work on that part I'd be happy to re-write the tests using our more modern types for you. (`states.State` instead of `terraform.State`, and if you' think that's confusing WELCOME TO MY EVERY DAY 😉 )

Thanks again!

2020-09-28 14:14 UTC, kulinacs commented
> Thanks for working on this, @kulinacs ! The changes look great, but I've requested changes to the tests.
> 
> The test changes are absolutely not something we'd expect a community contributor to know, and if you'd rather work on that part I'd be happy to re-write the tests using our more modern types for you. (`states.State` instead of `terraform.State`, and if you' think that's confusing WELCOME TO MY EVERY DAY 😉 )
> 
> Thanks again!

I'd greatly appreciate it if you'd re-write the tests for me. It's been a while since I've looked at the Terraform code and I don't want this PR blocked on me figuring out the type changes 😁

2020-09-28 15:45 UTC, mildwonkey commented
Apologies for the bad commit, I made a slight mess while rebasing against upstream :) hang tight, sorry for the extra noise!

2020-09-28 17:08 UTC, mildwonkey approved these changes
Looks great, thanks! 
I rebased your fork's taint-workspace branch against the upstream before modifying the tests, which wasn't strictly necessary. I apologize if I've messed up your fork at all (I'm having a bit of A Day in github).

2020-09-28 17:09 UTC, merged