Issue 26320 - lookup(): only treat map as unknown if it is wholly unknown
hashicorp/terraform pull request #26427
Opened 2020-09-30 12:30 UTC by OwenTuz

Fix for issue #26320 - this allows us to derive known values from partially known maps where we can, and may prevent unnecessary destroy/rebuild cycles during apply in some cases.

Based on @apparentlymart 's suggestions in the issue thread.

Most of this PR is changes to `primary_test.go` and `automation_test.go` as I have added a very basic regression test to the primary workflow. Happy to change or adjust this if you feel it would be cleaner/preferable to have a separate HCL file and test set for this.

2020-10-01 13:06 UTC, mildwonkey requested changes
Hi @OwenTuz ! Thank you for working on this. 

I really appreciate you adding test coverage, so please don't take this as criticism, just a request: 
I would prefer to see test coverage in the lookup tests rather than the e2e tests - the e2e tests are primarily focused on the _workflow_ and generally only run in circleCI, whereas the unit tests are something one can run locally and quickly.

Here's a test case that you could add to the lookup tests (in `collection_test.go`) which fails today and passes with your change:

```
{
	[]cty.Value{
		mapWithUnknowns,
		cty.StringVal("foo"),
	},
	cty.StringVal("bar"),
	false,
},
```

Thank you so much for submitting on this!

2020-10-01 13:21 UTC, OwenTuz commented
No problem at all, thanks for reviewing! I'm out today but will add that
tomorrow.

On Thu, 1 Oct 2020, 14:06 Kristin Laemmert, <notifications@github.com>
wrote:

> *@mildwonkey* requested changes on this pull request.
>
> Hi @OwenTuz <https://github.com/OwenTuz> ! Thank you for working on this.
>
> I really appreciate you adding test coverage, so please don't take this as
> criticism, just a request:
> I would prefer to see test coverage in the lookup tests rather than the
> e2e tests - the e2e tests are primarily focused on the *workflow* and
> generally only run in circleCI, whereas the unit tests are something one
> can run locally and quickly.
>
> Here's a test case that you could add to the lookup tests (in
> collection_test.go) which fails today and passes with your change:
>
> {
> 	[]cty.Value{
> 		mapWithUnknowns,
> 		cty.StringVal("foo"),
> 	},
> 	cty.StringVal("bar"),
> 	false,
> },
>
> Thank you so much for submitting on this!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hashicorp/terraform/pull/26427#pullrequestreview-500325305>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYSNPEULLV4EWN4AQXANETSIR5FJANCNFSM4R7A5YNA>
> .
>

2020-10-05 12:48 UTC, mildwonkey approved these changes
🎉 Thank you @OwenTuz , this looks great!

2020-10-05 12:48 UTC, merged

2020-10-05 12:51 UTC, mildwonkey commented
This is merged and the fix will be in Terraform v0.14 🎉