Update module-registry-protocol.html.md
hashicorp/terraform pull request #26639
Opened 2020-10-20 08:15 UTC by alevinetx

1: There is a mismatch in the segment labels for the version query URL (system vs provider)
2: There is a discrepancy between the documentation and the actual generated request for retrieving module source code (URL segments 4 vs 3)
 - There is no segment for "provider"

2020-10-20 08:15 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=26639)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=26639)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=26639).</sub>

2020-10-21 13:50 UTC, justincampbell requested changes
Thanks for the PR! I believe this correctly identifies that the `:system` and `:provider` variables are duplicated in the URLs and Parameters. `:provider` is the canonical name for this field, so if you can replace `:system` with `:provider` in your changes, we can merge this.

2020-10-26 22:23 UTC, alevinetx commented
@justincampbell  I wanted to make sure I did everything to fix and trigger that it's ready for you, and that it's just waiting on you, rather than I haven't done something needed.
 thanks !

2020-10-28 13:09 UTC, justincampbell approved these changes
This is great, thanks!

2020-10-28 13:09 UTC, merged