Adding PG_CONN_STR environment variable for PG backend.
hashicorp/terraform pull request #28205
Opened 2021-03-26 01:16 UTC by phillipsj

This adds the ability to use the PG_CONN_STR environment variable to set the connection string for the postgres backed. Fixes #27655

2021-03-26 01:16 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28205)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28205)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=28205).</sub>

2021-05-26 20:55 UTC, remilapeyre requested changes
Thanks for taking the time to write a PR @phillipsj! The change looks good and I think it should get released in the next minor version once we take care of the last details :)

2021-05-26 21:53 UTC, remilapeyre commented
I forgot to say that the documentation should also be updated with the change.

2021-05-29 16:54 UTC, phillipsj commented
I rebased on the lastest master, made the updates to the variable, added the test, and updated the docs. There is a failing test which I didn't touch, so I feel that came from the latest master.

2021-06-02 14:02 UTC, remilapeyre approved these changes
Thanks 🎉 !

2022-02-25 22:29 UTC, crw reviewed
Did these get missed in the conversion to no-underscores, or are these underscore names acceptable for another reason?

2022-02-25 22:29 UTC, crw commented on internal/backend/remote-state/pg/backend_test.go
> +		os.Setenv("PG_CONN_STR", "postgres://localhost/terraform_backend_pg_test?sslmode=disable")
Should these be `PGCONNSTR`?

2022-02-25 22:29 UTC, crw commented on internal/backend/remote-state/pg/backend_test.go
> +				os.Unsetenv("PG_CONN_STR")
Should these be `PGCONNSTR`?

2022-02-25 22:29 UTC, crw commented on internal/backend/remote-state/pg/backend_test.go
> +	return os.Getenv("PG_CONN_STR")
Should this be `PGCONNSTR`?

2022-02-25 22:30 UTC, crw commented
@phillipsj Thanks for the contribution! Can you check out my quick review, and also resolve the merge conflicts in the docs? We did a big doc migration recently that may have caused that issue, let me know if you need help and I'll pull in the doc expert.

2022-03-22 14:25 UTC, closed without merging