Fix yamldecode example from json to yaml
hashicorp/terraform pull request #28220
Opened 2021-03-28 15:18 UTC by vigohe

The `yamldecode` example it's a little bit confusing because it's using a `json` instead of `yaml`. So for better suit I change it to a yaml.

2021-03-28 15:18 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28220)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28220)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=28220).</sub>

2021-04-05 12:53 UTC, mildwonkey requested changes
Hi @vigohe ! Thanks for this, I can see how this can be confusing (even though it works, since json syntax is valid yaml).

I think it would be clearer if we kept the first example inline with the original (perhaps just `yamldecode("hello: world")`), since there's a later longer-form example which is more visibly yaml-specific syntax.

2021-04-05 15:39 UTC, vigohe commented
> Hi @vigohe ! Thanks for this, I can see how this can be confusing (even though it works, since json syntax is valid yaml).
> 
> I think it would be clearer if we kept the first example inline with the original (perhaps just `yamldecode("hello: world")`), since there's a later longer-form example which is more visibly yaml-specific syntax.

ok, fixed.

2021-04-05 17:40 UTC, mildwonkey commented
thank you!

2021-04-05 17:40 UTC, mildwonkey approved these changes

2021-04-05 17:41 UTC, merged