Document `\.` for regex function
hashicorp/terraform pull request #28234
Opened 2021-03-30 07:23 UTC by gtmtech

Documents https://github.com/hashicorp/terraform/issues/28232

2021-04-05 12:59 UTC, mildwonkey requested changes
Hi @gtmtech , thanks for submitting this! 

I'd like to make this more consistent with the other examples in this table.
Can you please move this new example towards bottom of this table, where there are other "Literal <thing>" and update the description to "Literal `.`" ?  
Thanks again!

2021-04-05 21:31 UTC, apparentlymart commented
The table row about `\*`, documented as "Literal `*` for any punctuation character `*`", was intended to be the documentation for this, because it's a general pattern that you can put a backslash in front of any punctuation metacharacter to escape its special meaning and get a literal of it.

Rather than adding a new row that makes it seem like `.` in particular has this behavior, perhaps there's a better way to explain that `\*` row in the table so it's clearer what it's referring to. Given that escaping is a common concern in regular expressions, I think it could be reasonable to add an extra note about it to the paragraph just before the table of sequences, which currently says the following:

> The pattern is a string containing a mixture of literal characters and special matching operators as described in the following table. Note that when giving a regular expression pattern as a literal quoted string in the Terraform language, the quoted string itself already uses backslash `\` as an escape character for the string, so any backslashes intended to be recognized as part of the pattern must be escaped as `\\`.

I'm thinking about adding an extra sentence after the first one, since the first sentence was already talking about "special matching operators":

> The pattern is a string containing a mixture of literal characters and special matching operators as described in the following table. To include a literal character that would normally be considered part of a matching operator, escape it by adding a `\` prefix.
>
> Note that when giving a regular expression pattern as a literal quoted string in the Terraform language, the quoted string itself already uses backslash `\` as an escape character for the string, so any backslashes intended to be recognized as part of the pattern must be escaped as `\\`. This includes any backslashes used to escape the matching operator characters, which must be interpreted by the regular expression engine rather than by the Terraform language parser.

(I also added a further paragraph to what is now the second paragraph in my new version, to make it as explicit as possible that the backslashes we're discussing here are regular expression backslashes rather than quoted string backslashes.)

2021-04-05 21:34 UTC, apparentlymart commented
(FWIW, our current documentation was derived from [the documentation of the underlying regular expression engine](https://github.com/google/re2/wiki/Syntax), and so a lot of the text we have on the page right now is unchanged from upstream, although I did consolidate several tables from the upstream docs into a single larger table in the Terraform docs.)

2021-04-19 15:04 UTC, gtmtech commented
@apparentlymart , 

> The table row about \*, documented as "Literal * for any punctuation character *", was intended to be the documentation for this

It's weird now I see that it says this, but I read the table over and over and didn't pick that up when I was tearing my hair out about how to get it to recognise a dot...

2021-04-21 07:17 UTC, gtmtech commented
@mildwonkey Hi , I've made the change you requested. You can now either accept/merge or reject it if @apparentlymart is not in favour - I wont update this PR again unless there are other changes you want.

2021-04-21 07:17 UTC, gtmtech commented
@mildwonkey Hi , I've made the change you requested. You can now either accept/merge or reject it if @apparentlymart is not in favour - I wont update this PR again unless there are other changes you want.

2021-07-26 21:46 UTC, laurapacilio commented
Hi All,

Reviving this :-). @gtmtech I see how you were confused thinking this was just about asterisks. I agree with @apparentlymart that adding a new row to this table feels like it's not quite the right play, as this works for any character and not just dot. I think it might be more helpful to qualify the description a bit with an example.  So, what if to the \* table row we say something like:

Literal `*` for any punctuation character `*` For example, `\.` is a literal `.`

@apparentlymart I'm not sure if you would still want to add the qualifying text to the paragraph above. I think if we add an example, we may not need the additional sentence. Looking at the page now, it looks like the second new paragraph you suggested has already been incorporated: https://www.terraform.io/docs/language/functions/regex.html

2021-08-24 21:51 UTC, laurapacilio requested changes
@gtmtech I added some suggestions based on the conversation thread that I think address your issue/hopefully help make this a bit clearer. Let me know what you think!

2021-08-24 21:51 UTC, laurapacilio commented on website/docs/language/functions/regex.html.md
> +| `\.`           | Literal `.`                                                                      |
```suggestion
```

2021-08-24 21:51 UTC, laurapacilio commented on website/docs/language/functions/regex.html.md
>  | `\*`           | Literal `*` for any punctuation character `*`                                    |
```suggestion
| `\*`           | Literal `*` for any punctuation character `*` For example, `\.` is a literal `.`                                    |
```

2022-03-12 17:04 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28234)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28234)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=28234).</sub>

2025-05-13 14:54 UTC, radeksimko commented
I have pulled the changes out into https://github.com/hashicorp/terraform/pull/37014 since this PR had no reactions in the recent years.

Thanks for the contribution.

2025-05-13 14:54 UTC, closed without merging