Prototype: Which resources "contributed to" the proposed plan?
hashicorp/terraform pull request #28944
Opened 2021-06-12 00:35 UTC by apparentlymart

This is a prototype of some internal analysis algorithms to allow us to ask more "global" questions about what refers to what within a configuration, considering also _indirect_ references.

This is not a final, shippable thing: the underlying algorithms are not complete for all possible expression types, the unit tests are lacking, and it's probably quite slow (though I've not measured). However, it was an experiment in ways to deal with some problems whose solutions seem to involve asking "what contributed to this expression?":

* When we detect that a `for_each` expression is invalid because it's unknown, it would help to know which resource references elsewhere in the configuration contributed to that result, because they'll probably be a good clue as to why the value ended up being unknown.
* When we're reporting changes detected outside of Terraform, we can potentially de-emphasize changes that don't seem to have actually contributed to any of the proposed changes, by walking backwards from the resources for which we've proposed changes to any other resources their configurations directly or indirectly refer to.

---

I used the second of the above as the vehicle to test this, and so also in this branch is a prototype of a possible adjustment to the "changed outside of Terraform" part of the plan UI where it'd only show a one-line summary if it detected a change to a resource that doesn't seem to have contributed to any of the proposed change actions, and thus in turn emphasize the ones that _could_ have contributed.

Some examples of that (although this illustrated functionality isn't complete, decided, nor really the main point of this prototype)...

Detected a change that seems relevant:

![a Terraform plan showing that a resource change outside of Terraform and that Terraform will take an action to undo that change](https://user-images.githubusercontent.com/20180/121759418-6d474280-cada-11eb-8910-62e2c8b88d0f.png)

Detected a change that doesn't seem relevant:

![a Terraform plan that mentions that a resource changed outside of Terraform but doesn't show details and doesn't propose any changes](https://user-images.githubusercontent.com/20180/121759449-9071f200-cada-11eb-81ba-06c8a330a508.png)

A mixture of relevant and not-so-relevant changes:

![two resources have changed outside of Terraform, but only one of them has an action planned for it and so the other one is only a one-line summary](https://user-images.githubusercontent.com/20180/121759475-aed7ed80-cada-11eb-9ebf-b3709824bc21.png)

A more interesting case where the second resource's configuration is derived from the first, and so the first is "relevant" even though it doesn't have any changes planned directly itself:

![Terraform detected an outside change to one resource and proposed a change for another, but it showed the outside change in full because the proposed change might be related to it](https://user-images.githubusercontent.com/20180/121759551-11c98480-cadb-11eb-951d-51fd2c00625f.png)

2022-03-12 17:00 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28944)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=28944)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=28944).</sub>

2022-03-30 23:28 UTC, dedayosam requested changes

2022-03-30 23:28 UTC, dedayosam commented on internal/command/views/plan.go
> +					"\nTerraform also changes to some other resource instances which don't seem to affect the plan:\n",
Hi @apparentlymart, not sure if this made it into our main repo PR (#30486). I checked and couldn't see it, but could be wrong. If it didn't, then ignore me :)

Missing a "detected" in the string. Should be "...Terraform also detected changes..."

2022-05-09 23:24 UTC, apparentlymart commented
This ultimately evolved into #30486, so we don't need this draft anymore.

2022-05-09 23:24 UTC, closed without merging