note that output of jsonencode is minified
hashicorp/terraform pull request #29088
Opened 2021-07-02 19:38 UTC by brenthc

The use of `jsonencode` to minify JSON values is useful, so note that in the docs explicitly. A data source or resource may produce a JSON string as an attribute that is not minified, and if needs to be used elsewhere minified, an expression like `jsonencode(jsondecode(data.some_data_source.json))` will do this.

2021-07-06 13:11 UTC, laurapacilio requested changes
Looks good - thank you for adding! Just one nit. Our link check is failing currently. Here's the output:

_Checking URLs in the following pages:
- website/docs/language/functions/jsonencode.html.md

Results:
=== Found broken links! ===
Fix before merging... or if they're not really broken, explain why.

website/docs/language/functions/jsonencode.html.md
  - Broken link: https://tools.ietf.org/html/rfc7159
    [302 Found] https://tools.ietf.org/html/rfc7159_

I think the actual link for RFC 5159 is: https://datatracker.ietf.org/doc/html/rfc7159. It redirects just fine, but could you update that in this file to see if it fixes the link check? If not, just leave a note on your PR about why the link isn't actually broken, and I'll approve.

Thank you! :)

2021-07-06 13:11 UTC, laurapacilio commented on website/docs/language/functions/jsonencode.html.md
> +The output of `jsonencode` is a minified representation of the input.
```suggestion
`jsonencode` outputs a minified representation of the input.
```

2021-08-23 18:10 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29088)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29088)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**1** out of **2** committers have signed the CLA.

- [x] fprimex
- [ ] brenthc

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=29088).</sub>

2021-08-23 18:11 UTC, brenthc commented on website/docs/language/functions/jsonencode.html.md
> +The output of `jsonencode` is a minified representation of the input.
Pushed the suggested wording change.

2021-08-23 18:24 UTC, laurapacilio commented
ignoring the link checker as it's just flagging a redirect - the link isn't actually broken.

2021-08-23 18:24 UTC, merged