chore: update lock message
hashicorp/terraform pull request #29409
Opened 2021-08-18 16:19 UTC by bodinsamuel

I have encountered an issue today with a connectivity lost that happened to let the lock in a bad state.
The message was helpful enough to make me understand this but not how to unlock, 
and I figured because you mention `"-lock=false"` there was no other command available.
But actually there is another command. Maybe it was intentional to not mention it, but as you are already mentioning a way to bypass the lock it's even better to displays to correct solution. 

Not putting the -force intentionally so that people still get the confirmation by copy/pasting.

I also think it could be highlighted in white and maybe with the LOCK_ID prefilled for convenience, but my skills in go stop there :D

2021-08-18 16:19 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29409)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29409)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=29409).</sub>

2022-01-18 13:06 UTC, bodinsamuel commented
Forgot about this one. Any feedback @apparentlymart ☺️

2022-01-19 00:28 UTC, crw commented
Just FYI @laurapacilio this is a change to the CLI help doc. I do not know if this information was purposefully excluded from the CLI help doc.

2022-01-28 20:45 UTC, laurapacilio commented
Hi @bodinsamuel - Thank you so much for submitting this!  I talked to engineering, and here's a summary of our thoughts:
- When we put full commands in the CLI help text that users can copy and paste, the assumption is that a lot of folks will do that automatically (kind of like when git gives you the commands to automatically push to a remote branch, etc.). We usually hesitate to do this because we wouldn't want folks to automatically take an action without fully understanding the implications.
- However, we do think the points you raised are valid, and so we think the right approach is to write something like: "If a previous unlock operation failed, use the "terraform force-unlock" command to override the lock."  This approach intentionally leaves out the LOCK_ID part. The rational is that if the user copies that directly and tries to run it, they'll get the usage messages for the "force-unlock" command (LOCK_ID is a required argument). We can then use those messages to give a bit more information about the consequences of this action.

All of this to say - would you be open to modifying your edits to remove the LOCK_ID portion and just reference the "force-unlock" command?  Let me know your thoughts, and thank you again for the suggestion! :-)

2022-05-20 23:41 UTC, crw commented
@bodinsamuel thanks for this contribution! Do you have any feedback regarding the above comment? Thanks again for this contribution, we appreciate it!

2022-05-30 16:08 UTC, bodinsamuel commented
Oops sorry for the lag, I had completely forgotten about this. 
I understand your points totally make sense, I have removed the LOCK_ID. Feel free to modify my PR and merge/close if needed ☺️

2022-06-27 22:24 UTC, laurapacilio requested changes
Thank you very much for understanding and for agreeing to go a more general route with the recommendation. What do you think of the proposed edit? If you merge that change in, I'd be happy to merge this PR for you. :-)

2022-06-27 22:24 UTC, laurapacilio commented on internal/command/clistate/state.go
> +terraform force-unlock`
```suggestion
If a previous unlock operation failed, you can use the `terraform force-unlock` command to override the lock.
```

2025-05-13 11:09 UTC, radeksimko commented
👋🏻 We would be happy to accept the contribution with the consideration of @laurapacilio's suggestions and accepted CLA per https://github.com/hashicorp/terraform/pull/29409#issuecomment-901249268

If you are still interested in contributing it, feel free to open a new PR, I'm going to close this one as it has been without reaction for a couple of years now.

2025-05-13 11:09 UTC, closed without merging