Document config in plan file for http backend
hashicorp/terraform pull request #29519
Opened 2021-09-03 14:36 UTC by njdart

This attempts to document the storage of backend configuration in plan files when the config was provided with either `-backend-config` or directly written in HCL. This only changes the docs for the HTTP backend which is where [I discovered this when using gitlab managed Terraform state](https://gitlab.com/gitlab-org/gitlab/-/issues/338482), but a more global location may be better suited such as the backend overview page or a page on the plan command?

This also partially resolves https://github.com/hashicorp/terraform/issues/29195

2021-09-03 14:36 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29519)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29519)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=29519).</sub>

2022-05-21 00:01 UTC, crw commented
Thanks for this submission! Between the time this was submitted and now, we have migrated our docs to a new format, which resulted in all of the files being renamed. This change would now need to be made to https://github.com/hashicorp/terraform/blob/main/website/docs/language/settings/backends/http.mdx. However, before making that change, I am including @laurapacilio to review whether we would be likely to accept this change. 

Thanks again for your submission and your patience! We appreciate it!

2022-06-07 16:19 UTC, laurapacilio commented
Hello! This is an incredibly useful addition, and I'm very sorry that we didn't review it before we migrated the content! @njdart would you be willing to re-open this PR with these changes ini the new .mdx files? If so, I'd be happy to review it and get it merged in.

I would also be willing to help open the PR if necessary. I agree that better docs are required here to help prevent folks from "gotchas" associated with how config is stored.

2022-06-07 21:19 UTC, laurapacilio requested changes
I'm reviewing for wording and flow, and I have a couple of suggestions. Let me know what you think! I'm also going to ask someone from engineering to review this from a technical point of view.

Thank you!

2022-06-07 21:19 UTC, laurapacilio commented on website/docs/language/settings/backends/http.mdx
> +~> **Warning!** It is highly recommended that you supply sensitive or dynamic configuration to the HTTP backend via environment variables.
```suggestion
~> **Warning!** We recommend using environment variables to supply sensitive or dynamic configuration to the HTTP backend. If you use `-backend-config` or include the values directly in HCL, Terraform will [store these values in plain-text in plan files](#configuration-cached-in-plan-files).
```

2022-06-07 21:19 UTC, laurapacilio commented on website/docs/language/settings/backends/http.mdx
> +Supplying values to the backend using either `-backend-config` or in HCL directly will result in these [values being stored in plain-text in plan files.](#configuration-cached-in-plan-files)
```suggestion
```

2022-06-09 19:02 UTC, laurapacilio commented
Hi @njdart - Your work sparked a great conversation between me and engineering on this topic. We realized that this warning actually applies to many of the backends, beyond just HTTP. So I opened a separate PR (inspired by this one!) where we give users a bit more context about the consequences of hardcoding credentials, etc. And then we added a note on all relevant backend pages to warn users about this and link them back to that explanation for more details.

https://github.com/hashicorp/terraform/pull/31213

What do you think? If you like this new PR, my suggestion is that we close out this PR and merge the new one I linked, so that all backend users can benefit from this information. Thank you again for your contributions to our docs! :-)

2022-06-11 09:06 UTC, njdart commented
Happy with https://github.com/hashicorp/terraform/pull/31213

2022-06-11 09:06 UTC, closed without merging