Return exit code 1 when source address doesn't exist
hashicorp/terraform pull request #29839
Opened 2021-10-30 17:54 UTC by pedrocb

Terraform no longer returns 0 exit code when `terraform state mv` is given a source address that doesn't exist
Fixes issue #29365

2021-10-30 17:54 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29839)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=29839)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=29839).</sub>

2021-11-04 14:47 UTC, alisdair requested changes
Thanks for this fix! We'd like to have test coverage for it. If you could [add a unit test to cover this case similar to the other unit tests](https://github.com/hashicorp/terraform/blob/main/internal/command/state_mv_test.go), I'd be happy to merge. Or please let me know if you'd like help writing the test and I can push a commit to this branch.

2022-02-13 00:26 UTC, pedrocb commented
Added an unit test @alisdair

2022-02-14 20:18 UTC, alisdair approved these changes
Thanks again!

2022-02-14 20:20 UTC, merged