Simplified the list
hashicorp/terraform pull request #30228
Opened 2021-12-21 07:39 UTC by RSwarnkar

2021-12-21 07:39 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=30228)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=30228)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=30228).</sub>

2022-02-01 22:58 UTC, laurapacilio requested changes
Thank you for this contribution! One suggestion for you and then I'd be happy to merge this in. :-)

2022-02-01 22:58 UTC, laurapacilio commented on website/docs/language/values/variables.mdx
>  * Any `-var` and `-var-file` options on the command line, in the order they
Hi! Thank you for this change :-) My suggestion is - can we remove the parentheses around "This includes variables set by a Terraform Cloud workspace."  The two sets of parentheses in a row is a bit overwhelming visually.  If you can make that change, I'd be happy to merge this for you!

2022-06-15 23:24 UTC, crw commented
Closing due to lack of response.

2022-06-15 23:24 UTC, closed without merging