bump cloud.google.com/go/storage from 1.10.0 to 1.18.2  backend/gcs
hashicorp/terraform pull request #30276
Opened 2021-12-30 12:19 UTC by zotrix

update cloud.google.com/go/storage to fix issue #29656 also fix  update from dependabot see #29777

2021-12-30 12:19 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=30276)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=30276)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=30276).</sub>

2022-04-07 14:52 UTC, kmoe commented
@hashicorp/terraform-google, could you take a look at this?

2022-10-11 19:26 UTC, SarahFrench requested changes
Hi @zotrix 👋 , sorry that this PR has been waiting on a review for so long! I'm currently doing some work on the `gcs` backend and came across your PR and the associated issue.

If you have time, could you please update your fork and re-do updating the dependencies? Then I can review this and get it merged. Or if you don't have time I could make a new PR add you as a co-author?

Let me know how you'd like to do things

2022-11-21 14:31 UTC, SarahFrench commented
Superseded by https://github.com/hashicorp/terraform/pull/32203

2022-11-21 14:31 UTC, closed without merging