Adds documentation to `substr` function to cover when `length` exceeds input length
hashicorp/terraform pull request #30483
Opened 2022-02-07 04:13 UTC by bpar476

The `substr` function allows the `length` parameter to be longer than the remaining characters in the input after the offset. This is useful for when you want to truncate a string to a maximum number of characters. However, the documentation isn't clear on this so I had to do a test deployment to confirm the behaviour after finding the behaviour in an old issue https://github.com/hashicorp/terraform/issues/15751

2022-02-07 04:13 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=30483)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=30483)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=30483).</sub>

2022-02-14 22:22 UTC, laurapacilio requested changes
Thank you! A suggestion to make the copy a bit more concise. Let me know what you think!

2022-02-14 22:22 UTC, laurapacilio commented on website/docs/language/functions/substr.mdx
> +will be the length of all remaining characters.
```suggestion
If the length is greater than the length of the string, the substring
will be the length of all remaining characters.
```

2022-02-14 23:22 UTC, bpar476 commented on website/docs/language/functions/substr.mdx
> +will be the length of all remaining characters.
Looks good!

2022-02-15 16:08 UTC, alisdair approved these changes

2022-02-15 16:27 UTC, laurapacilio approved these changes
Perfect - thank you!

2022-02-15 16:27 UTC, merged