Handle -input=false in cloud integration
hashicorp/terraform pull request #30858
Opened 2022-04-13 17:45 UTC by sebasslash

For non-interactive contexts, Terraform is typically executed with the flag `-input=false`. However for runs that are not set to auto approve, the cloud integration will prompt a user for approval input even with the flag being set to false. This PR enables the cloud integration to know the value of the input flag and use it to determine whether or not to ask the user for input (i.e during run confirmation).

If `-input` is set to false and the run cannot be auto approved, the cloud integration will throw an error
stating run confirmation can no longer be handled in the CLI and that they must do so through the browser.

## To Test
1) Create a Terraform configuration using the cloud integration.
2) Run `~/go/bin/terraform apply -input=false`
3) Expect an error.

2022-04-18 15:51 UTC, brandonc reviewed
I think I found another confirmation when a policy soft fails in backend_policy.go checkPolicy

... unless op.UIOut is nil when --input is false but I don't think it is.

2022-04-19 19:31 UTC, sebasslash commented
> I think I found another confirmation when a policy soft fails in backend_policy.go checkPolicy
> 
> ... unless op.UIOut is nil when --input is false but I don't think it is.

It is not. I've added the `input` field to the `Cloud`struct which will track the value of `-input`. The field gets configured in `backend_cli.go`

2022-04-20 21:04 UTC, brandonc requested changes
Just a few nitpicks

2022-04-20 21:04 UTC, brandonc commented on internal/cloud/backend_common.go
> +	errNeedsCloudConfirmation = errors.New("Cannot confirm apply due to -input=false. Please handle run confirmation in the browser.")
I think errors in go should not be capitalized or end in punctuation. We also seem to use the term "UI" instead of "browser"

2022-04-20 21:04 UTC, brandonc commented on internal/cloud/backend_common.go
> +				return fmt.Errorf("Cannot override soft failed policy checks when -input=false. Please open the run in the browser to override.")
Same concern as above

2022-04-26 18:19 UTC, brandonc approved these changes
🏁

2022-04-26 18:25 UTC, merged

2022-04-26 20:49 UTC, brandonc approved these changes
I smoke tested this and it worked