Added example with function argument expansion
hashicorp/terraform pull request #31011
Opened 2022-05-06 07:30 UTC by dleser

Even if the expansion with three dots is explicity mentioned in https://www.terraform.io/language/expressions/function-calls#expanding-function-arguments the additional example would have helped me a lot as it is a common use case to "flatten" a list of maps.

2022-05-06 07:30 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31011)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31011)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=31011).</sub>

2022-05-17 15:58 UTC, laurapacilio requested changes
Hello! Thank you for submitting this to us! We would like to request that you add a brief explanation of the example, like my suggestion below, that links to the documentation we have about the expansion symbol. We think this will help readers better understand what's going on in the example and why it's included. 

Let me know what you think, thank you!

2022-05-17 15:58 UTC, laurapacilio commented on website/docs/language/functions/merge.mdx
> +
```suggestion
The following example uses the expansion symbol (...) to transform the value into separate arguments. Refer to [Expanding Function Argument](/language/expressions/function-calls#expanding-function-arguments) for details.

```
> merge([{a="b", c="d"}, {}, {e="f", c="z"}]...)
{
  "a" = "b"
  "c" = "z"
  "e" = "f"
}
```
```

2022-06-15 23:41 UTC, crw commented
@dleser can you please review @laurapacilio's comment, above? Thanks!

2022-06-17 18:47 UTC, crw commented
@laurapacilio back to you!

2022-06-28 20:49 UTC, laurapacilio approved these changes
Thank you! 🚀

2022-06-28 20:50 UTC, merged