Update syntax.mdx
hashicorp/terraform pull request #31204
Opened 2022-06-08 09:39 UTC by parkchoongho

fix wrong grammar

2022-06-08 09:39 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31204)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31204)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=31204).</sub>

2022-06-09 20:38 UTC, laurapacilio requested changes
Thank you for catching this! I have a tiny suggestion as I think we want to refer to the entire thing as a singular example.

2022-06-09 20:38 UTC, laurapacilio commented on website/docs/language/resources/syntax.mdx
> +You can use `precondition` and `postcondition` blocks to specify assumptions and guarantees about how the resource operates. The following examples create a precondition that checks whether the AMI i
```suggestion
You can use `precondition` and `postcondition` blocks to specify assumptions and guarantees about how the resource operates. The following example creates a precondition that checks whether the AMI is properly configured.
```

2022-06-13 09:00 UTC, parkchoongho commented
> Thank you for catching this! I have a tiny suggestion as I think we want to refer to the entire thing as a singular example.

Oh, I think that's a better one!

2022-06-13 15:20 UTC, laurapacilio approved these changes
🚀

2022-06-13 15:20 UTC, merged