feat: add startswith and endswith funcs
hashicorp/terraform pull request #31220
Opened 2022-06-09 22:01 UTC by FooBartn

Purpose: Add `startswith` and `endswith` built-in functions to Terraform

Per the issue referenced below, these are functions that the Terraform team is willing to accept due to the broad use case and interest. I have not submitted to the `terraform` repo before, so my apologies if I missed any conventions or standards. I tried to keep it as close to the other code that I saw as possible. If there's anything that should be changed please let me know.

Referencing Issue: https://github.com/hashicorp/terraform/issues/28209

2022-06-09 22:01 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31220)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31220)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=31220).</sub>

2022-06-10 23:57 UTC, crw commented
Thanks for this submission! It is in the queue to be reviewed. Thanks again!

2022-06-29 14:03 UTC, alisdair requested changes
This is great, thanks for the contribution! This behaviour makes sense to me and I checked it out locally.

I requested a few additional test cases inline. We'll also need documentation for these new functions, which means:

- [Adding a new page to the `language/functions` directory](https://github.com/hashicorp/terraform/tree/main/website/docs/language/functions), with the same format as other string functions
- [Adding the page to the `language-nav-data.json` file](https://github.com/hashicorp/terraform/blob/main/website/data/language-nav-data.json)
- [Updating the `layouts/language.erb` template](https://github.com/hashicorp/terraform/blob/main/website/layouts/language.erb)

I'm adding our Technical Writer as a reviewer on this PR, who should be able to help review the docs once you've written them.

2022-06-29 15:31 UTC, laurapacilio commented
Hi there! I'm excited to see this new functionality, and thank you to @alisdair for pointing out the need for docs! :) I think a great approach to maintain the format we use for these pages is to copy and paste the .mdx from an existing string function page and then modify it for the new function that you're adding. 

I would love to review your docs changes once you've drafted them. If you have questions at any point in the process, please just leave a comment in this PR and tag me, and I'd be happy to help.

Thank you again for your contributions!

2022-06-30 23:19 UTC, FooBartn commented
@alisdair Unsure what broke with Vercel. Let me know if there's anything I need to do.

@laurapacilio Please feel free tear apart my first run at documentation 😄

2022-07-04 15:34 UTC, alisdair reviewed
Thanks! I'll leave the docs review for Laura, but the code is ✅ from me.

I think the Vercel failure is because we don't have entries in the language-nav-data.json file at the top level of the `functions` part of the tree. Other functions have an entry for their virtual sub-section (which you've added) and a separate `hidden` entry at the `functions` level, later in the file. For example: https://github.com/hashicorp/terraform/blob/f74e93a84ab47f6e060ff124211adb38c7c8112f/website/data/language-nav-data.json#L861-L862

2022-07-06 16:01 UTC, FooBartn commented
> I think the Vercel failure is because we don't have entries in the language-nav-data.json file at the top level of the `functions` part of the tree. Other functions have an entry for their virtual sub-section (which you've added) and a separate `hidden` entry at the `functions` level, later in the file. For example:

That was it! Thank you!

2022-07-14 15:10 UTC, laurapacilio commented on website/docs/language/functions/startswith.mdx
> +  and returns true if the first given string contains the given value at its end
```suggestion
- [`endswith`](/language/functions/endswith) takes two values: a string to check and a suffix string. The function returns true if the first string ends with that exact suffix value.
```

2022-07-14 16:16 UTC, laurapacilio approved these changes
Approving because I think this is great! Just a few final minor wording nits to remove an extra word. Would you mind merging those in as well?

Otherwise, @alisdair I think this is ready - I'd like you to do the honors, since this contains code as well as docs :)

2022-07-14 16:16 UTC, laurapacilio commented on website/docs/language/functions/endswith.mdx
> +  The endswith function takes two values: a string to check and a suffix string. It returns true if the first string ends with that exact suffix value.
```suggestion
  The endswith function takes two values: a string to check and a suffix string. It returns true if the first string ends with that exact suffix.
```

2022-07-14 16:20 UTC, FooBartn commented
> Approving because I think this is great! Just a few final minor wording nits to remove an extra word. Would you mind merging those in as well?
> 
> Otherwise, @alisdair I think this is ready - I'd like you to do the honors, since this contains code as well as docs :)

I like it! I went with language that was similar to another set of docs, but this is clearer. Thank you!

2022-07-14 17:13 UTC, merged

2022-07-14 17:13 UTC, alisdair commented
Thanks again! 🎉