doc change to match behavior
hashicorp/terraform pull request #31460
Opened 2022-07-18 16:13 UTC by fnickels

Fixes Bug reported in https://github.com/hashicorp/terraform/issues/31442

This PR is a 4th alternate implementation - documentation change to match code behavior.

Use instead if the following PRs are not workable:
* https://github.com/hashicorp/terraform/pull/31456 
* https://github.com/hashicorp/terraform/pull/31452 
* https://github.com/hashicorp/terraform/pull/31443

2022-07-21 00:28 UTC, crw commented
Thanks for these documentation changes. I'll run these past the docs team for review.

2022-07-22 15:46 UTC, laurapacilio requested changes
Hi @fnickels - thanks for adding this! I'm making a suggested edit to help with clarity and flow. Please let me know if I have misunderstood your intended meaning. Do you feel comfortable merging it in?

@crw After this, I would like a quick engineering technical 👍 as well - this is a case I'm not super familiar with and I want to make sure engineering is okay with this. Especially since there has been discussion about `-chdir` in other threads. Thank you!

2022-07-22 15:46 UTC, laurapacilio commented on website/docs/cli/config/config-file.mdx
> +for checking for the existence of the `terraform.d/plugins` directory.*
```suggestion
system. This behavior changes when you use the `-chdir` option with the `init` command. In that case, Terraform checks for the `terraform.d/plugins` directory in the launch directory and not in the directory you specified with `-chdir`.
```

2022-07-27 19:08 UTC, laurapacilio approved these changes
🚀  @crw - over to eng. for a final 👍

2022-07-27 21:43 UTC, crw commented
For future reference: I believe this comment confirms the behavior as described in these docs changes. However, I'll queue this up for final review. 

https://github.com/hashicorp/terraform/issues/31442#issuecomment-1185646259

2022-07-29 21:53 UTC, merged