docs: fix typo regarding unknown values
hashicorp/terraform pull request #31508
Opened 2022-07-25 19:17 UTC by wzyboy

In Terraform plans, unknown values are displayed as `(known after apply)`. This PR updates the docs to reflect this.

2022-07-25 19:17 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31508)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31508)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=31508).</sub>

2022-07-26 15:58 UTC, crw commented
Thanks for the submission! I'll send this over to the docs team.

2022-07-27 17:53 UTC, mgarrell777 requested changes
@wzyboy Thanks very much for your contribution. Once you've made this change, I'll work on getting the PR merged.

2022-07-27 17:53 UTC, mgarrell777 commented on website/docs/language/expressions/references.mdx
>  To allow expressions to still be evaluated during the plan phase, Terraform
@wzyboy Thank you very much for your efforts on the PR. I would like to make a couple of additional changes to the paragraph. Would you mind updating your PR to replace this paragraph with the following:

"Terraform uses special unknown value placeholders for information that it cannot predict during the plan phase. The Terraform language automatically handles unknown values in expressions. For example, adding a known value to an unknown value automatically produces an unknown value as a result."

2022-07-29 18:48 UTC, laurapacilio approved these changes
Thank you!

2022-08-18 18:34 UTC, wzyboy commented
@mgarrell777 Is there anything I can do for this PR?

2022-08-19 12:43 UTC, mgarrell777 approved these changes
@wzyboy Looks good to me. Thanks very much for your effort on this PR.

2022-10-25 15:07 UTC, merged