Update init.mdx
hashicorp/terraform pull request #31682
Opened 2022-08-24 06:38 UTC by kmchau428

Suspect it is a typo...

2022-08-24 06:38 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31682)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=31682)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=31682).</sub>

2022-08-24 13:17 UTC, alisdair commented
This is not a typo, `-force-copy` implies `-migrate-state`: https://github.com/hashicorp/terraform/blob/036db86c1fc7f64bc03ff75150e50456b28c9f2b/internal/command/init.go#L83-L87

Can you suggest a clearer way to word that?

2022-08-25 02:48 UTC, kmchau428 commented
> This is not a typo, `-force-copy` implies `-migrate-state`:
> 
> https://github.com/hashicorp/terraform/blob/036db86c1fc7f64bc03ff75150e50456b28c9f2b/internal/command/init.go#L83-L87
> 
> Can you suggest a clearer way to word that?

If I understand correctly, does that mean cloning the existing state to the new backend?

2022-08-25 12:59 UTC, alisdair commented
That's what `-migrate-state` does, yes.

2022-08-26 01:06 UTC, kmchau428 reviewed
Made the intention of `-migrate-state` with `-force-copy` more explicit.

2022-08-26 15:27 UTC, alisdair requested changes

2022-08-26 15:27 UTC, alisdair commented on website/docs/cli/commands/init.mdx
> +initiating the new backend with the existing state.
I think there's a disconnect here between the intent of the original documentation and your proposal. What I'd suggest instead here to clarify the text which caused the misunderstanding is replacing the "This implies […]" sentence with something like:

> Enabling `-force-copy` also automatically enables the `-migrate-state` option.

2022-08-29 14:01 UTC, alisdair approved these changes
Thanks!

2022-08-29 14:01 UTC, merged