Add some clarification on Cloud workspace names and workspace tags
hashicorp/terraform pull request #32211
Opened 2022-11-13 20:24 UTC by dvusboy

It wasn't clear during migration that the tags are the driver in workspace grouping, and since it isn't possible to rename a workspace after the fact, regrets can happen.

I have a repository with two related configurations, one existed as a sub-directory and has a couple of local workspaces with states. The top-level configuration only has the default workspace with state. I attempted a migration, because I would like to share the states with my colleague, and started with the sub-directory. Then when I started the migration at the parent directory, because of the lack of other local workspaces, the flow was different and I didn't get to set a name pattern based on the existing workspace. So, I ended up with a very generic name that I cannot change (I should submit a feature request on that).

In hindsight, all of it makes sense since the `cloud` setting is tied to the repository, and should be configuration-specific. But if the documentation has been a bit more forthright, perhaps I won't be in this predicament.

1.4.x

## Draft CHANGELOG entry
Clarify the loose relation between Cloud workspace names and tags in the documentation.

### DOCUMENTATION

2022-11-13 20:24 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=32211)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=32211)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=32211).</sub>

2022-11-14 21:34 UTC, crw commented
Thanks for this submission, I have let the docs team know this is here for review.

2023-07-14 22:05 UTC, trujillo-adam requested changes
Thanks for working on this. I think we can do more work to clarify the information in this section. We'll open a PR after we finish this one. 

We appreciate your help.

2023-07-14 22:05 UTC, trujillo-adam commented on website/docs/cli/cloud/settings.mdx
> +    have a strong correlation with the underlying configuration. This option conflicts with `name`.
```suggestion
  - `tags` - (Optional) Specifies set of Terraform Cloud workspace tags. Terraform uses the tags to group Terraform
    Cloud workspaces, regardless of their names and configurations.
    You can use a working directory with any workspace that has all of the specified tags. To switch between workspaces or create new workspaces, use the [`terraform workspace` commands](/cli/workspaces). New workspaces created inherit any tags that have been applied to the current workspace. We recommend applying tags when a workspace has a strong correlation with the underlying configuration. This option conflicts with `name`.
```
Just a few suggestions for consistency with our style guide.

2024-07-25 23:10 UTC, crw approved these changes

2024-07-25 23:18 UTC, crw commented
It appears to me these changes were superseded by a later PR, likely per https://github.com/hashicorp/terraform/pull/32211#pullrequestreview-1531093865, a superseding PR was opened. I am going to go ahead and close this, please let me know if I missed a detail here.

2024-07-25 23:18 UTC, closed without merging

2024-07-25 23:48 UTC, dvusboy commented
Thanks.