Additional documentation for cli graph command
hashicorp/terraform pull request #32262
Opened 2022-11-21 17:19 UTC by sheilman16

Fixes #

## Target Release

1.4.x

## Draft CHANGELOG entry

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-

2022-11-21 17:19 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=32262)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=32262)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=32262).</sub>

2022-11-22 00:26 UTC, crw commented
Thanks for this submission. I'll put it in the docs team queue to review. Please sign the CLA when you get a chance! Thanks again!

2023-04-26 20:39 UTC, rkoron007 requested changes
Hello! 👋  Apologies for the late response here, but this PR looks great with a suggested tiny tweak for styling. Thank you for your contribution!

2023-04-26 20:39 UTC, rkoron007 commented on website/docs/cli/commands/graph.mdx
> +Alternatively, `dot` can export to other image file formats by changing the flag input:
This looks great to me with some small tweaks and an additional line between the sentence and the code block:
```suggestion
Alternatively, `dot` can export other image file formats if you change the flag input:

```

2025-05-13 14:37 UTC, closed without merging