Fix SRO authorization bug when token is fetched from cloud config
hashicorp/terraform pull request #32666
Opened 2023-02-10 22:13 UTC by sebasslash

An authorization bug was reported: #32665 

In the cloud backend, we instantiate a new http client in order to fetch the redacted plan and generate the plan output. The auth token for this client was configured by calling `b.token()` which only sources the token from your CLI configuration, ignoring any token that was set in the cloud config itself. 

In order to make use of the token returned by the cloud config, I've added a new `token` field to the cloud backend, since the `Configure()` receiver is the only place we have access to the config. I've also renamed `b.token()` to be more descriptive about where the token is being fetched to avoid any further confusion. 

## Target Release

1.4.x

## Draft CHANGELOG entry

### BUG FIXES

 

-

2023-02-13 15:06 UTC, alisdair commented
Note that this will need the `1.4-backport` label added, as merges to `main` now target a future 1.5 release.

2023-02-16 17:48 UTC, brandonc approved these changes

2023-02-16 18:17 UTC, brandonc requested changes
I have an idea to run by you before you merge this so I changed my review temporarily.

2023-02-16 23:16 UTC, brandonc commented
Here is an alternative fix: https://github.com/hashicorp/terraform/pull/32698

2023-02-21 23:27 UTC, brandonc commented
@sebasslash I've decided to fix the disco credentials token issue in a different way, because I don't want to write the token to the CLI login file prematurely. I think there may be a more ideal fix for what I had in mind. So I think this approach is actually what we should ship in 1.4

2023-02-21 23:38 UTC, brandonc approved these changes

2023-02-21 23:40 UTC, merged