Update README.md
hashicorp/terraform pull request #33092
Opened 2023-04-26 15:14 UTC by 0xchabbi

fix dead-link and change naming to have right understanding. (Add Peramlink instead of copy path)

Fixes #

## Target Release

1.4.x

## Draft CHANGELOG entry

### NEW FEATURES | UPGRADE NOTES | ENHANCEMENTS | BUG FIXES | EXPERIMENTS

 

-

2023-04-26 18:26 UTC, 0xchabbi commented
@kmoe @crw

2023-04-26 20:36 UTC, crw requested changes

2023-04-26 20:36 UTC, crw commented on docs/README.md
> +* [Contributing to Terraform](https://github.com/hashicorp/terraform/blob/7ae272fe3184b3c0c6dc066b2d1bc86ac14606bd/.github/CONTRIBUTING.md): a complete guideline for those who want to contribute to t
The correct link is: `.github/CONTRIBUTING.md` as in:

```
[Contributing to Terraform](.github/CONTRIBUTING.md)

2023-04-26 20:37 UTC, crw commented
Hi @0xchabbi, thanks for this! Please make the correction indicated and I'd be happy to merge this.

2023-04-26 21:15 UTC, 0xchabbi commented
Thank you for the correction! @crw !

2023-04-26 21:44 UTC, merged

2023-04-26 21:45 UTC, crw reviewed
lgtm

2023-04-30 21:25 UTC, 0xchabbi commented
Hi @crw !
Still showing the 404 page if you click the link. Could we set it with permalink instead of path?

2023-05-02 23:22 UTC, crw commented
I see, I was not paying attention to the location of the file. We do not want to have to update this document every time we update `CONTRIBUTING.md`, so hard-linking to a particular snapshot of the file is not desirable. If you can hard-link it so that it always shows the `main` branch version of `CONTRIBUTING.md`, I suppose that would be OK. Alternatively, we can see if you can just use a `../` in the path to refer to the correct relative path, if that is how GitHub thinks about files.

2023-05-02 23:24 UTC, crw commented
Yes, that (`../`) fixed it. Thanks for the heads-up!

2023-05-02 23:38 UTC, 0xchabbi commented
Good to know how GitHub thinks about files! :) 
Thank you