Support endpoint for the COS backend
hashicorp/terraform pull request #33656
Opened 2023-08-10 07:18 UTC by lyu571

Support endpoint for the COS backend

## Target Release
1.6.x

## Draft CHANGELOG entry

### ENHANCEMENTS

-  Provide the endpoint way to access Tencentcloud COS. This method can provide support for internal network URLs for customers.

2023-08-10 07:56 UTC, lyu571 commented
Hi @crw @likexian plz help to review my PR.

2023-08-10 08:01 UTC, likexian commented
LGTM

2023-08-11 03:15 UTC, lyu571 commented
HI @crw  plz help to review my PR. :)

2023-08-25 16:39 UTC, kmoe requested changes
Some docs comments

2023-08-25 16:39 UTC, kmoe commented on internal/backend/remote-state/cos/backend.go
> +				Description: "The custom endpoint for the COS API. eg: http://cos-internal.{Region}.tencentcos.cn, both http or https can be accepted.",
```suggestion
				Description: "The custom endpoint for the COS API, e.g. http://cos-internal.{Region}.tencentcos.cn. Both HTTP and HTTPS are accepted.",
```

2023-08-25 16:39 UTC, kmoe commented on internal/backend/remote-state/cos/backend.go
> +				Description: "The root domain of the API request, Default is `tencentcloudapi.com`.",
```suggestion
				Description: "The root domain of the API request. Default is tencentcloudapi.com.",
```

2023-08-25 16:39 UTC, kmoe commented on internal/backend/remote-state/cos/backend.go
> +		log.Printf("[DEBUG][backend] set domain for TencentCloud api client. domain:[%s]", b.domain)
```suggestion
		log.Printf("[DEBUG] Backend: set domain for TencentCloud API client. Domain: [%s]", b.domain)
```

2023-08-25 16:39 UTC, kmoe commented on internal/backend/remote-state/cos/backend.go
> +	// set url as endpoint when it provided
```suggestion
	// set url as endpoint when provided
```

2023-08-25 16:39 UTC, kmoe commented on internal/backend/remote-state/cos/backend.go
> +		log.Printf("[DEBUG][backend] set cos url as:[%s]", newUrl)
```suggestion
		log.Printf("[DEBUG] Backend: set COS URL as: [%s]", newUrl)
```

2023-08-25 16:39 UTC, kmoe commented on internal/backend/remote-state/cos/backend_test.go
> +		t.Skip("This test require setting TF_COS_APPID environment variables")
```suggestion
		t.Skip("This test requires setting the TF_COS_APPID environment variable")
```

2023-08-25 16:39 UTC, kmoe commented on website/docs/language/settings/backends/cos.mdx
> +- `domain` - (Optional) The root domain of the API request. Defaults to `tencentcloudapi.com`. It supports environment variables `TENCENTCLOUD_DOMAIN`.
```suggestion
- `domain` - (Optional) The root domain of the API request. Defaults to `tencentcloudapi.com`. It supports the environment variable `TENCENTCLOUD_DOMAIN`.
```

2023-08-25 16:39 UTC, kmoe commented on website/docs/language/settings/backends/cos.mdx
> +If provided with an endpoint url, Terraform will attempt to access COS backend by the `endpoint` configuration or environment variables `TENCENTCLOUD_ENDPOINT`.
```suggestion
If provided with an endpoint URL, Terraform will attempt to access the COS backend by the `endpoint` configuration or the environment variable `TENCENTCLOUD_ENDPOINT`.
```

2023-08-25 16:39 UTC, kmoe commented on website/docs/language/settings/backends/cos.mdx
> +A typical endpoint like this: `http://cos-internal.{Region}.tencentcos.cn`, both http or https can be accepted.
```suggestion
A typical endpoint looks like this: `http://cos-internal.{Region}.tencentcos.cn`. Both HTTP and HTTPS are accepted.
```

2023-08-25 17:41 UTC, crw commented
Hi @lyu571, as long as you are OK accepting this docs changes, we can merge this PR. Thanks!

2023-08-29 12:22 UTC, lyu571 commented
> Hi @lyu571, as long as you are OK accepting this docs changes, we can merge this PR. Thanks!

Hi @crw I've accepted all docs comments. Plz continues the processing. Thank you.

2023-08-30 14:09 UTC, kmoe approved these changes

2023-08-30 14:09 UTC, merged

2023-09-13 08:37 UTC, lyu571 commented
Hi @kmoe and @crw, the feature `endpoint` was required by our customer who already waited a while. Seems the latest(1.5.7) Terraform release doesn't include this PR. Could you put the release plan for this PR with high priority? 

Maybe change the milestone from 1.6.0 to 1.5.x?

2023-09-13 14:58 UTC, crw commented
Hi @lyu571, the first version of the product with this feature will be `1.6.0`. You should be able to see it in `1.6.0-beta1`. Thanks!

2023-09-14 02:35 UTC, lyu571 commented
> Hi @lyu571, the first version of the product with this feature will be `1.6.0`. You should be able to see it in `1.6.0-beta1`. Thanks!

Oh, I see.
Looks like this version is a pre-release version that our customer cannot use in an official way.
May I ask what time the official `1.6.0` be released/available?

2023-09-14 15:24 UTC, crw commented
Early October. `1.6.0-beta2` was released today, then there will be two release candidate releases.

2023-09-15 02:02 UTC, lyu571 commented
> Early October. `1.6.0-beta2` was released today, then there will be two release candidate releases.

ok. Thanks!