Update requirements.mdx
hashicorp/terraform pull request #33912
Opened 2023-09-19 16:21 UTC by mrpavan

Provider source address delimiter separator / was within the hostname portion before closing bracket ']' and same has been corrected
file - /main/website/docs/language/providers/requirements.mdx

Original Line 120
`[<HOSTNAME>/]<NAMESPACE>/<TYPE>`

Updated
`[<HOSTNAME>]/<NAMESPACE>/<TYPE>`

Fixes #
https://github.com/hashicorp/terraform/issues/33911#issue-1903332105

## Target Release

1.5.x

## Draft CHANGELOG entry

### UPGRADE NOTES 

 

-  Provider source address delimiter placement correction from `[<HOSTNAME>/]<NAMESPACE>/<TYPE>` to `[<HOSTNAME>]/<NAMESPACE>/<TYPE>`

2023-09-19 16:21 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=33912)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=33912)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=33912).</sub>

2023-09-20 13:26 UTC, alisdair requested changes
Thanks for the contribution, but this is not correct. Please see the discussion in the original issue. While the hostname is optional, if omitted, the leading slash must not be present.

The clearest way I can imagine to explain the source address format was mentioned in the linked issue: give two examples, one with the hostname, and one without. This will require some rewording of this section of the docs.

2023-09-20 14:02 UTC, mrpavan commented
As recommended by the @alisdair @apparentlymart , reverted provider format and added example for valid provider formats as below 

Examples of valid provider formats include 
- `NAMESPACE/TYPE`
- `HOSTNAME/NAMESPACE/TYPE` 

Thanks,
Pavan

2023-09-20 14:05 UTC, alisdair reviewed
Thanks! I have a couple of formatting suggestions inline, but after that this looks good to merge to me.

2023-09-20 14:05 UTC, alisdair commented on website/docs/language/providers/requirements.mdx
> +`[<HOSTNAME/>]<NAMESPACE>/<TYPE>`
I think this was a typo in your revert:

```suggestion
`[<HOSTNAME>/]<NAMESPACE>/<TYPE>`
```

2023-09-20 14:05 UTC, alisdair commented on website/docs/language/providers/requirements.mdx
> +Examples of valid provider formats include
```suggestion
Examples of valid provider source address formats include:
```

2023-09-20 14:05 UTC, alisdair commented on website/docs/language/providers/requirements.mdx
> +- `HOSTNAME/NAMESPACE/TYPE`
```suggestion
- `HOSTNAME/NAMESPACE/TYPE`
```

2023-09-20 14:17 UTC, alisdair approved these changes

2023-09-20 14:18 UTC, merged