Update environment-variables.mdx
hashicorp/terraform pull request #34271
Opened 2023-11-18 05:23 UTC by inetmiguel

Previous sentence mentions that the variables will be checked last for a value, this is confusing and leads to think that environment variables are the last evaluated and most important in precedence order.

No github issue or discussion started since it is a very small contribution to documentation not code, please accept or refuse as convenient. Thank you!

2023-11-18 05:23 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=34271)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform?pullRequest=34271)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform?pullRequest=34271).</sub>

2023-11-28 19:16 UTC, crw requested changes

2023-11-28 19:16 UTC, crw commented on website/docs/cli/config/environment-variables.mdx
> +Environment variables can be used to set variables. The environment variables must be in the format `TF_VAR_name` and these will be checked for a value. For example:
To maintain the original intention of the sentence, perhaps:

> [...] in the format `TF_VAR_name`. Environment variables are the lowest in the precedence order to be checked for a value. [...]

2023-11-28 19:16 UTC, crw commented
Thanks for this submission! Please sign the CLA for this to be considered for inclusion. Thanks again!

2025-05-13 14:58 UTC, radeksimko commented
If you are still interesting in contributing this patch and considering the suggestions made by @crw you are welcome to submit a new PR. I'm closing this one since it was without a reaction for a couple of years.

2025-05-13 14:58 UTC, closed without merging