Rebrand Terraform Cloud to HCP Terraform
hashicorp/terraform pull request #35050
Opened 2024-04-22 19:30 UTC by sebasslash

Rebrand Terraform Cloud to HCP Terraform

## Target Release

1.8.2

## Draft CHANGELOG entry

### ENHANCEMENTS 

 

-  Rebrands all references from "Terraform Cloud" to "HCP Terraform"

## More Notes
You should expect no functional changes regarding the rebrand:
- All CLI output that contains "Terraform Cloud", "TFC/E" has been changed to instead show "HCP Terraform" and/or "Terraform Enterprise". 
- The `cloud` block will not be renamed
- Env vars such as `TF_CLOUD_ORGANIZATION`, `TF_CLOUD_PROJECT`, etc are **not** being renamed.

2024-04-22 21:10 UTC, Maed223 approved these changes

2024-04-22 21:22 UTC, crw commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: For issues and feature requests related to the HCP Terraform or Terraform Enterprise, please submit a HashiCorp support request or email tf-cloud@hashicorp.support
"the" HCP Terraform, is that correct usage?

2024-04-22 21:54 UTC, sebasslash commented on internal/cloud/backend.go
> +// TODO: REMOVE WHEN go-tfe's IsCloud() returns true for
Yep, I will need rebranded go-tfe released first to fix this.

2024-04-23 00:31 UTC, nfagerlund reviewed
Question: should this PR wait for a release of the rebranded go-tfe? 

This mostly seems to be in good shape. There's some amount of inconsistency around when we do or don't use the "cloud or enterprise" construction; this PR doesn't exactly add more of it, but I should ask — how much of it do you think is worth addressing at this time? We can hammer out a rubric for when to do it and when not to, and I can go through with a fine-toothed comb to enforce it... but I wanna let you be the judge of whether it's worth it, because you know more about the marketing timelines for this than we do.

2024-04-23 00:31 UTC, nfagerlund commented on internal/command/meta_backend_migrate.go
> +would you like to rename your workspaces? Enter 1 or 2.
Hmm, this instance of the "x or y" compromise is somewhat more frustrating than most of the others. 

We don't currently have the name available in the `promptMultiStateMigrationPattern` helper function, but that func's call site _does_ have access to a full cloud backend (in opts.Destination), so it ought to be possible to do a type-assert, grab the .AppName() off it, and pass it into the helper as a second arg. 

Reckon it's worth it? The approach would also be applicable to some of the other messages in this zone.

2024-04-23 00:31 UTC, nfagerlund commented on internal/command/show.go
> +		return nil, errUnusable(fmt.Errorf("can't show a saved cloud plan unless the current root module is connected to HCP Terraform"), "cloud plan")
I think this one should get the "or", alas.

2024-04-23 00:31 UTC, nfagerlund commented on internal/command/test.go
> +                        remotely using HCP Terraform. You must specify the
Should this one get the "or" also?

2024-04-23 12:50 UTC, BrianMMcClain approved these changes

2024-04-23 12:50 UTC, BrianMMcClain commented on internal/command/meta_backend_migrate.go
> +	// destination is always HCP Terraform (TFC).
```suggestion
	// destination is always HCP Terraform.
```

2024-04-23 12:50 UTC, BrianMMcClain commented on internal/rpcapi/cli.go
> +			// Cloud only because we're using HCP Terraform's integration
Flagging this, but a reference to "Terraform Cloud" remains split across lines 80 and 81

2024-04-23 13:04 UTC, BrianMMcClain approved these changes

2024-04-23 20:04 UTC, sebasslash commented on internal/cloud/testdata/plan-json-full/plan-redacted.json
> -{"plan_format_version":"1.1","resource_drift":[{"address":"tfcoremock_simple_resource.example","mode":"managed","type":"tfcoremock_simple_resource","name":"example","provider_name":"registry.terrafor
That's okay, we'll leave it as is given this is just a test fixture.

2024-04-23 20:26 UTC, nfagerlund approved these changes
All right, this looks good enough to work with! The "HCP or TFE" curse is as frustrating as ever when it comes to making all this text work sensibly, but your mix of approaches and fallbacks here seems roughly as good as one could hope for. 👍🏼

2024-04-23 20:27 UTC, merged

2024-05-03 21:12 UTC, Yuksell06 commented on internal/command/meta_backend_migrate.go
> +	// destination is always HCP Terraform (TFC).
[]()

2024-05-03 21:14 UTC, Yuksell06 requested changes
Herşey çok daha güzel olacak

2024-05-03 21:29 UTC, Yuksell06 commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: For issues and feature requests related to the HCP Terraform or Terraform Enterprise, please submit a HashiCorp support request or email tf-cloud@hashicorp.support
Enes